services:
  next:
    image: naterkana/onesqa-frontend:0.1
    container_name: next-frontend
    ports:
      - "3001:3001" 
    environment:
      NODE_ENV: production
      GRAPHQL_ENDPOINT_INTERNAL: "http://host.docker.internal:4001/graphql"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
